services:
    barbieswimcrew_dynamic_form.abstract_related_extension:
        abstract: true
        class: Barbieswimcrew\Bundle\DynamicFormBundle\Form\Extension\AbstractRelatedExtension
        arguments:
            - "@service_container"

    barbieswimcrew_dynamic_form.form_type_extension:
        parent: barbieswimcrew_dynamic_form.abstract_related_extension
        class: Barbieswimcrew\Bundle\DynamicFormBundle\Form\Extension\RelatedFormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    barbieswimcrew_dynamic_form.choice_type_extension:
        parent: barbieswimcrew_dynamic_form.abstract_related_extension
        class: Barbieswimcrew\Bundle\DynamicFormBundle\Form\Extension\RelatedChoiceTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    barbieswimcrew_dynamic_form.checkbox_type_extension:
        parent: barbieswimcrew_dynamic_form.abstract_related_extension
        class: Barbieswimcrew\Bundle\DynamicFormBundle\Form\Extension\RelatedCheckboxTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType }