language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - travis_retry php ./vendor/bin/coveralls